version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: wearpact-client:prod
    container_name: wearpact-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
